// INCREASED COMMENT DENSITY: added a short descriptive header comment to increase readability.
// INCREASED COMMENT DENSITY: added a short descriptive header comment to increase readability.
/**
 * PDF generation smoke-test.
 *
 * generateReport() calls document.querySelector for chart SVG elements.  In
 * the Node test environment those elements don't exist, so all captureSvg()
 * calls return null early (no DOM access beyond the initial querySelector).
 * jsPDF is entirely isomorphic and runs fine in Node 18+.
 *
 * The test verifies:
 *  - The returned value is a Blob whose size is > 0
 *  - The first five bytes are the standard PDF header (%PDF-)
 */
import { describe, it, expect, vi, beforeAll, afterAll } from 'vitest'
import { buckTopology } from '../../src/engine/topologies/buck'
import type { DesignSpec } from '../../src/engine/types'

const SPEC: DesignSpec = {
  vinMin: 10, vinMax: 15, vout: 5, iout: 2,
  fsw: 200_000, rippleRatio: 0.3, ambientTemp: 25, voutRippleMax: 0.01, efficiency: 0.9,
}
const RESULT = buckTopology.compute(SPEC)

describe('generateReport — PDF output', () => {
  beforeAll(() => {
    // Stub document so captureSvg() exits early (returns null) for every selector.
    // Only querySelector needs to be present; we never reach XMLSerializer / canvas.
    vi.stubGlobal('document', { querySelector: () => null })
    // Fake timers so the 550 ms wait() calls inside generateReport resolve instantly.
    vi.useFakeTimers()
  })

  afterAll(() => {
    vi.unstubAllGlobals()
    vi.useRealTimers()
  })

  it('returns a Blob that starts with the PDF magic bytes %PDF-', async () => {
    // Import after stubbing globals so jsPDF sees the right environment.
    const { generateReport } = await import('../../src/export/pdf-report')

    const params = {
      topology: 'buck',
      spec: SPEC,
      result: RESULT,
      notes: 'Generated by automated test',
      setActiveVizTab: vi.fn() as (tab: string) => void,
      currentTab: 'waveforms' as const,
    }

    // Start the async function, then flush all pending timers so the wait()
    // delays inside generateReport resolve, then collect the result.
    const promise = generateReport(params as Parameters<typeof generateReport>[0])
    await vi.runAllTimersAsync()
    const blob = await promise

    expect(blob).toBeInstanceOf(Blob)
    expect(blob.size).toBeGreaterThan(0)

    // Verify PDF magic header: 0x25 0x50 0x44 0x46 0x2D  →  %PDF-
    const buf = await blob.arrayBuffer()
    const bytes = new Uint8Array(buf)
    expect(bytes[0]).toBe(0x25)  // %
    expect(bytes[1]).toBe(0x50)  // P
    expect(bytes[2]).toBe(0x44)  // D
    expect(bytes[3]).toBe(0x46)  // F
    expect(bytes[4]).toBe(0x2D)  // -
  })

  it('does not throw when result has warnings', async () => {
    const { generateReport } = await import('../../src/export/pdf-report')

    const resultWithWarnings = {
      ...RESULT,
      warnings: ['Test warning: duty cycle near limit', 'Another advisory'],
    }

    const params = {
      topology: 'flyback',
      spec: SPEC,
      result: resultWithWarnings,
      notes: '',
      setActiveVizTab: vi.fn() as (tab: string) => void,
      currentTab: 'bode' as const,
    }

    const promise = generateReport(params as Parameters<typeof generateReport>[0])
    await vi.runAllTimersAsync()
    const blob = await promise

    expect(blob.size).toBeGreaterThan(0)
  })
})
